version: '3.8'

services:
  app:
    build: .
    image: diploma-back:latest
    container_name: diploma-app
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/netology
      - SPRING_DATASOURCE_USERNAME=student
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=netology
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U student -d netology" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data: